### ISSUE TITLE
Build fails on AppVeyor

### ISSUE THREAD

**Issue by andrejewski** [canjs/can-zone#127]
Starting with https://github.com/canjs/can-zone/commit/c2c83c67c7ba04e7fb7a409e878b36b5763c98d4, AppVeyor builds began to fail.

The failure is due to a Testee timeout for some set of tests. See https://github.com/canjs/can-zone/pull/126 builds for an example for the failure.

I tested can-zone in my Window/IE9 emulator and all tests passed.

**Comment by matthewp** [comment]
I think it's an issue with testee launching multiple tests in Appveyor. To unblock I'm limiting the tests on Appveyor to the main `test.html file only.

**Comment by matthewp** [comment]
This is fixed now.
