### ISSUE TITLE
Simplified overrides API

### ISSUE THREAD

**Issue by matthewp** [canjs/can-zone#45]
Related to https://github.com/canjs/can-ssr/issues/122

If you are just overriding objects it would be good if you could do:

```js
wait(fn, {
  overrides: {
    document: localDocument
  }
});
```

This assumes you are always overriding properties on the global, which isn't always the case. Will need to take a little bit of thinking.

**Comment by matthewp** [comment]
Maybe `globals` is a better name for this option.

**Comment by matthewp** [comment]
This is my current thinking, to have a really robust zone library I think we need:

## Zone

A **Zone** is a JavaScript context in which overrides (need a better name) are applied to globals. 

```js
var zone = new Zone({
  document: myDocument,
  location: myLocation,
  overrides: [
    function(){
      return new Override(foo.bar, "baz", function(oldBaz){
        return newBaz;
      })
    }
  ]
});

zone.run(fn).then(function(){
  // Zone has exited
});
```

## ZoneOptions

A Zone takes an options object which provides globals to override and hooks into when tasks are run.

### globals

These are global properties which we want to override. A few of these, `document`, `location` can also be provided as ZoneOptions for simplicity.

```js
var options = {
  document: myDocument,
  globals: {
    FOO: 'foo'
  }
};

var zone = new Zone(options);
```

### onBeforeXhr

Runs before an XHR request is run. Returning from this function will prevent the request from happening.

```js
new Zone({
  onBeforeXhr: function(xhr, url){
    xhr.responseText = '{"foo": "bar"}';
    return xhr;
  }
});
```

### onAfterXhr

A hook that runs after an XHR request is complete.

```js
new Zone({
  onAfterXhr: function(xhr){
    // maybe i'll save the result for later
  }
});
```

## Task

A **Task** represents a function that runs inside of a Zone. A task is a callback to an asynchronous function; the callback to a `setTimeout`, the callback to `Promise.prototype.then`.

```js
var task = new Task(zone, fn);
var result = task.run(ctx, args);
```

### Task.prototype.run

Calls `fn` with a context (the `this` value) and `args`, an array of arguments. Returns whatever `fn` returns.

Since tasks run within a Zone, all of the zone's global overrides are applied before `fn` is called.

**Comment by justinbmeyer** [comment]
Could we also support:
```
var zone = new Zone({
  document: myDocument,
  location: myLocation,
  "foo.bar": newBaz
});
```

Also, does `Override` have to be a type?

**Comment by justinbmeyer** [comment]
How can you get the current zone and add other overwrites, globals, hooks, etc?

**Comment by matthewp** [comment]
> How can you get the current zone and add other overwrites, globals, hooks, etc?

By forking the current zone:

### Zone.current

This is a global that represents the currently running Zone.

### Zone.prototype.fork

Create a new Zone using a ZoneOptions that extends the currently running Zone. This means that the currently running Zone's globals overrides will be applied to the forked zone and any other overrides will also be added.

```js
var newZone = Zone.current.fork({
  document: anotherDoc,
  afterTask: function(){
    // This is called after every task.
  }
});

newZone.run(fn).then( ...
```

**Comment by matthewp** [comment]
> Could we also support:

> var zone = new Zone({
  document: myDocument,
  location: myLocation,
  "foo.bar": newBaz
});

We can support the dot notation, yes, but I think those should be nested under a `globals` option. I think common globals like `document` and `location` can go directly on ZoneOptions for convenience, but I don't want globals to "take over" what ZoneOptions is about.

> Also, does Override have to be a type?

Internally it makes sense to be one, externally perhaps not, but I can't think of a better way to describe what it does. It needs the Object being overridden, a Property name, and a factory function to create the new value. Any suggestion for a nicer API here are welcome.

**Comment by justinbmeyer** [comment]
Why does it ned the factory function to create the new value?

**Comment by justinbmeyer** [comment]
What confuses me is:

```
overrides: [
    function(){
      return new Override(foo.bar, "baz", function(oldBaz){
        return newBaz;
      })
    }
  ]
```

There are two functions, I'm not sure why, and a seemingly excessive amount of "override" labeling.  

These are `overrides` as indicated by `overrides:`.  I'm not sure why I also have to create an Override instance.  Is there something else that could possibly be returned?

Also, why two functions?  I would assume that all of these would be run when `.run` is called ... which presumably would typically immediately after the `new Zone()` call.

**Comment by matthewp** [comment]
> Why does it ned the factory function to create the new value?

If you're overriding a function you often want access to the old value of the function, the factory provides this, for example:

```js
new Override(window, "setTimeout", function(oldSetTimeout){
  return function(){
    // do stuff
    return oldSetTimeout.apply(this, arguments);
  };
});
```

**Comment by matthewp** [comment]
> here are two functions, I'm not sure why, and a seemingly excessive amount of "override" labeling.

> These are overrides as indicated by overrides:. I'm not sure why I also have to create an Override instance. Is there something else that could possibly be returned?

It could be an object instead:

```js
overrides: [
  {
    obj: foo.bar,
    prop: "baz",
    factory: function(oldBaz){
      return newBaz;
    }
  }
]
```

Is this that much better though?

> Also, why two functions? I would assume that all of these would be run when .run is called ... which presumably would typically immediately after the new Zone() call.

It shouldn't be two functions. It is currently, but `overrides` should just be Override instances (unless we figure out a better way to define these).

**Comment by justinbmeyer** [comment]
> Is this that much better though?

Yes, at least twice as good :-).

>  you often want access to the old value of the function

Couldn't you just do:

```
var old = global.somewhere;

overrides: {
  "somewhere": myThing(old)
}
