### ISSUE TITLE
Deprecation warning in Chrome ~2

### ISSUE THREAD

**Issue by Macrofig** [canjs/can-zone#84]
Getting following warning using 0.5.7

> Invoking 'send()' on a sync XHR during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

![image](https://cloud.githubusercontent.com/assets/2633542/18037944/5818b0fe-6d5d-11e6-87f4-3dc7ee5cfad7.png)

Chrome Version 52.0.2743.116 (64-bit)

**Comment by matthewp** [comment]
This is probably caused by something else and not can-zone, can-zone is maybe reporting the error because it is last-in-line.  Let me know if you have more info or a way to reproduce.

**Comment by matthewp** [comment]
~2

**Comment by matthewp** [comment]
Going to close for now, let me know if you have more info.
