### ISSUE TITLE
jQuery Animations

### ISSUE THREAD

**Issue by mickmcgrath13** [canjs/can-zone#86]
jQuery animate appears to use `requestAnimationFrame` (which, unfortunately, falls back to [setInterval](https://github.com/jquery/jquery/blob/e4fd41f8fa4190fbbb6cb98cf7ace64f6e00685d/src/effects.js#L668)).  

If my browser has requestAnimationFrame, I would expect the following:
```
  console.log("----zonetest: Start");
  new Zone().run(function(){
      $(".content").animate({
          "opacity":0
      }, 1000, function(){
        console.log("----zonetest: animaton done");
      });
  }).then(function(){
      console.log("----zonetest: zone run done");
  });
```
to output:
```
----zonetest: Start
----zonetest: animaton done
----zonetest: zone run done
```

..but it outputs this:
```
----zonetest: Start
----zonetest: zone run done
----zonetest: animaton done
```

Any ideas on what it would take to get this to work?

**Comment by mickmcgrath13** [comment]
Also, for what it's worth, this doesn't work as I would expect either:
```
  new Zone().run(function(){
      return new Promise(function(res){
        $(".content").animate({
            "opacity":0
        }, 1000, function(){
          console.log("----zonetest: animaton done");
          res();
        });
      });
  }).then(function(){
      console.log("----zonetest: zone run done");
  });
```

..it outputs:
```
----zonetest: Start
----zonetest: zone run done
----zonetest: animaton done
```

**Comment by mickmcgrath13** [comment]
I'm looking to use this for can-animate.  If we didn't have to make the users of can-animate call a callback or resolve a promise to notify that their animation is complete, that'd be super awesome (i.e. zones handle jQuery animations).

**Comment by matthewp** [comment]
Looks like jQuery Animate uses setInterval, not requestAnimationFrame. can-zone doesn't currently support setInterval but it [might be added](https://github.com/canjs/can-zone/issues/78) in the future.

Until then you can use [Zone.waitFor](http://canjs.github.io/canjs/doc/can-zone.waitFor.html) to wait on stuff can-zone doesn't natively support.  [Here's a jsbin](http://jsbin.com/jufapozati/1/edit?html,js,console) showing your example.

**Comment by mickmcgrath13** [comment]
This works as a workaround for now.  Thanks.

**Comment by mickmcgrath13** [comment]
Also, I closed this because it was created as a "help wanted" ticket, and help was provided and useful.  I could see a use for a "jQuery Animations" issue for can-zone (possibly just to have a test or two for $el.animate)?
